# if it says core its just core not core/v1
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:
    app: first-app
    tier: backend
  ports:
    - protocol: "TCP"
      # outside world port
      port: 80
      # port application is listening on
      targetPort: 8080
  type: LoadBalancer
